# This enforces to selected at least 'n' elements of each solution size (if available).
# Depending on the multithreading parameter, this may result in more.
# The only way to select all is to select an unreasonably high number
pick-random: 100
# This decides, if java files should be checked for if they compile and selected based on their performance.
# This increases the processing time drastically
do-compile: True
# This describes the number of parallel file assignment attempts (e.g., the compilation of java files)
multithreading-poolsize: 12

problems:
  2016 Qualification Round -- Revenge of the Pancakes:
    round: 6254486
    task: 5634697451274240
  2016 Round 1A -- The Last Word:
    round: 4304486
    task: 5631989306621952
  2016 Qualification Round -- Counting Sheep:
   round: 6254486
   task: 5652388522229760
  2016 Round 1C -- Senate Evacuation:
    round: 4314486
    task: 5753053697277952
  2016 Round 3 -- Forest University (only one problem set):
    round: 3224486
    task: 5125089213284352
  2016 Finals -- Family Hotel:
    round: 7234486
    task: 5751639981948928
  2019 Qualification Round -- You Can Go Your Own Way:
    round: 0000000000051705
    task: 00000000000881da
  2020 Round 1A -- Pattern Matching:
    round: 000000000019fd74
    task: 00000000002b1353
  2020 Qualification Round -- Vestigium (only one problem set):
    round: 000000000019fd27
    task: 000000000020993c
